@token = 
@id_usuario =684ff4a6ff9ac0e7b35c663a
@id_compra = 
@id_producto = 


### Crear usuario
POST http://localhost:3000/api/v1/usuarios
Content-Type: application/json

{
    "name": "Jordi",
    "email": "jordi@example.com",
    "password": "jordi123"
}


### LOGIN para conseguir token
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "jaime@example.com",
    "password": "jaime123"
}


### Obtener usuario por ID
GET http://localhost:3000/api/v1/usuarios/{{id_usuario}}


### Actualizar usuario completo
PUT http://localhost:3000/api/v1/usuarios/{{id_usuario}}
Content-Type: application/json

{
    "name": "JaimeActual",
    "email": "jaime@example.com",
    "password": "jaime123"
}


### Actualizar contraseña
PUT http://localhost:3000/api/v1/usuarios/{{id_usuario}}/password
Content-Type: application/json

{
    "oldPassword": "123456",
    "newPassword": "nueva1234"
}

### Asignar rol admin (requiere token)
PUT http://localhost:3000/api/v1/usuarios/{{id_usuario}}/admin
Authorization: Bearer {{token}}

