@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODgyMGY2NmQwOTM3YWU1MTI1MWQ3YWYiLCJuYW1lIjoiSmFpbWUiLCJyb2xlIjoidXNlciIsImlhdCI6MTc1MzYxNDA2NSwiZXhwIjoxNzUzNjI0ODY1fQ.KQWz9qhSO2xSRNYCrPAcu_ejfnHum_E5CgItiIs8f78
@id_usuario =68820f66d0937ae51251d7af
@id_compra = 
@id_producto = 


### Crear usuario
POST http://localhost:3000/api/v1/usuarios
Content-Type: application/json

{
    "name": "María",
    "email": "mariamaria@gmail.com",
    "imagen": "https://i.pinimg.com/564x/01/be/d0/01bed0d659eec5f891448841d85accd4.jpg",
    "password": "mariamaria12345",
    "role": "admin"
}


### LOGIN para conseguir token
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "jaimejaime@gmail.com",
    "password": "jaimejaime12345"
}


### Obtener usuario por ID
GET http://localhost:3000/api/v1/usuarios/{{id_usuario}}


### Actualizar usuario completo
PUT http://localhost:3000/api/v1/usuarios/{{id_usuario}}
Content-Type: application/json

{
    "name": "Jaime",
    "email": "jaimejaime@gmail.com",
    "password": "jaime123",
    "role": "admin"
}


### Actualizar contraseña
PUT http://localhost:3000/api/v1/usuarios/{{id_usuario}}/password
Content-Type: application/json

{
    "oldPassword": "123456",
    "newPassword": "nueva1234"
}

### Asignar rol admin (requiere token)
PUT http://localhost:3000/api/v1/usuarios/{{id_usuario}}/admin
Authorization: Bearer {{token}}

