@token = 
@id_usuario = 
@id_compra = 
@id_producto = 6880ce7541e168d30c708c4c

### Crear producto (sin token)
POST http://localhost:3000/api/v1/productos
Content-Type: application/json

{
    "title": "Invento de Surf Quiksilver Union 6' Salsa",
    "type": "Sea",
    "description": "Para la práctica de deportes de agua",
    "img": "https://missionsurfshop.com/media/catalog/product/cache/b43f938c028a23568e5c708857f5b368/l/e/leash-quiksilver-union-6-salsa.jpg",
    "price": 10
}

### Obtener todos los productos
GET http://localhost:3000/api/v1/productos

### Obtener producto por ID
GET http://localhost:3000/api/v1/productos/{{id_producto}}

### Actualizar producto
PUT http://localhost:3000/api/v1/productos/{{id_producto}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Tabla Snow Actualizada",
    "type": "snowboard",
    "description": "Mejorada para freestyle",
    "img": "https://www.everydaycalifornia.com/cdn/shop/articles/unnamed_b75e57b9-4789-4d4f-8fc3-c42122668e57.jpg?v=1686240476&width=1204",
    "price": 279.99
}

### Eliminar producto
DELETE http://localhost:3000/api/v1/productos/{{id_producto}}
Authorization: Bearer {{token}}
