# Usuarios: 
@dominio=http://localhost:3000
@uid=67d316aa763ffcf07798df19
@token= 123456789

### registrar nuevo usuario
POST {{dominio}}/api/v1/auth/register
Content-Type: application/json

{
    "name": "JaimeNEBOT",
    "email": "jaimeNEBOT@cei.es",
    "password": "ceiNEBOT0ul"
}

### login de usuario Jaime
POST {{dominio}}/api/v1/auth/login
Content-Type: application/json

{
    "email": "jaime10@cei.es",
    "password": "cei10ul"
}

### Obtener datos de Jaime
GET {{dominio}}/api/v1/auth/me
Authorization: Bearer {{token}}

