# Productos: 
@dominio=http://localhost:3000
@uid=67d316aa763ffcf07798df19
@pid=675849485
@compraId= 67584948

### Crear una compra para un usuario
POST http://localhost:3000/api/v1/usuarios/662c65eb2aa3c2e4e9b7a9f3/compras
Content-Type: application/json

{
    "productoId": "662c6a342aa3c2e4e9b7a9f9",
    "title": "tabla skate",
    "type": "snow",
    "price": "12"
}

### Obtener todas las compras (Admin)
GET http://localhost:3000/api/v1/compras

### Obtener compras de un usuario
GET http://localhost:3000/api/v1/usuarios/662c65eb2aa3c2e4e9b7a9f3/productos-comprados

### Actualizar una compra
PUT http://localhost:3000/api/v1/ussuarios/662c65eb2aa3c2e4e9b7a9f3/compras/662c8dd12aa3c2e4e9b7aa21
Content-Type: application/json

{
    "cantidad": 2
}
