
# Productos: 
@dominio=http://localhost:3000
@uid=67d316aa763ffcf07798df19
@pid=3

### Crear producto en venta para un usuario
POST http://localhost:3000/api/v1/usuarios/662c65eb2aa3c2e4e9b7a9f3/productos
Content-Type: application/json

{
    "title": "Skate Pro",
    "type": "Tabla profesional para trucos avanzados",
    "price": 120
}

### Obtener todos los productos (Admin)
GET http://localhost:3000/api/v1/productos

### Obtener productos en venta de un usuario
GET http://localhost:3000/api/v1/usuarios/662c65eb2aa3c2e4e9b7a9f3/productos-en-venta

### Actualizar producto
PUT http://localhost:3000/api/v1/productos/662c6a342aa3c2e4e9b7a9f9
Content-Type: application/json

{
    "price": 100,
    "disponible": false
}

### Eliminar producto
DELETE http://localhost:3000/api/v1/productos/662c6a342aa3c2e4e9b7a9f9
