# Usuarios: 
@dominio=http://localhost:3000
@uid=67d316aa763ffcf07798df19


### Crear producto
POST {{dominio}}/api/v1/productos
Content-Type: application/json

{
    "nombre": "Jaime",
    "email": "jaime@cei.es"
}

### Obtener todas los usuarios
GET {{dominio}}/api/v1/productos

### Obtener usuario
GET {{dominio}}/api/v1/productos/{{uid}}

### Editar usuarios
PUT {{dominio}}/api/v1/productos/{{uid}}
Content-Type: application/json

{
    "nombre": "Pedro",
    "email": "pedro@hola.com"
}

### Eliminar usuarios
DELETE {{dominio}}/api/v1/productos/{{uid}}